blank_issues_enabled: false
contact_links:
  - name: 🖥️ ASF-PluginTemplate issue
    url: https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose
    about: This repository doesn't accept issues. If your matter relates to our plugin template issue, feel free to use the main ASF repo for that purpose. If this page is part of the third-party plugin for ASF, then it means that its author didn't configure GitHub issues for his repository.
