blank_issues_enabled: false
contact_links:
  - name: 🖥️ ASF-PluginTemplate issue
    url: https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose
    about: Please use the main ArchiSteamFarm repo for that purpose, this one accepts PRs only
